import Vue from 'vue'
import {
  Button,
  Swipe,
  SwipeItem,
  Col,
  Row,
  CountDown,
  Cell,
  CellGroup,
  Card,
  Image as VanImage,
  Lazyload,
  Icon,
  Grid,
  GridItem,
  Tabbar,
  TabbarItem,
  Form,
  Field,
  Uploader,
  Empty,
  Tab,
  Tabs,
  GoodsAction,
  GoodsActionIcon,
  GoodsActionButton,
  Overlay,
  ShareSheet,
  Slider,
  NoticeBar,
  RadioGroup,
  Radio,
  Tag,
  Checkbox,
  CheckboxGroup,
  Popup,
  Stepper,
  List,
  Search,
  Sticky,
  Sidebar,
  SidebarItem
} from 'vant';

Vue.use(Button);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Col);
Vue.use(Row);
Vue.use(CountDown);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Card);
Vue.use(VanImage);
Vue.use(Lazyload);
Vue.use(Icon);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Form);
Vue.use(Field);
Vue.use(Uploader);
Vue.use(Empty);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(GoodsAction);
Vue.use(GoodsActionIcon);
Vue.use(GoodsActionButton);
Vue.use(Overlay);
Vue.use(ShareSheet);
Vue.use(Slider);
Vue.use(NoticeBar);
Vue.use(RadioGroup);
Vue.use(Radio);
Vue.use(Tag);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Popup);
Vue.use(Stepper);
Vue.use(List);
Vue.use(Search);
Vue.use(Sticky);
Vue.use(Sidebar);
Vue.use(SidebarItem);
